### ISSUE TITLE
error in converting bhive to tfrecord

### ISSUE THREAD

**Issue by ronghongbo** [google/gematria#121]
Hello, I am trying the example at https://github.com/google/gematria/blob/main/g3doc/obtaining-training-data.md  to convert bhive to tfrecord, and get the following error: 
```
(env) ~/gematria$ curl -L https://raw.githubusercontent.com/ithemal/bhive/5f1d50077ac0779fd227b261dcf517862c7104bd/benchmark/throughput/skl.csv > skl.csv
(env) ~/gematria$ env USE_BAZEL_VERSION=6.4.0  ../bazelisk-linux-amd64  run //gematria/datasets/python:import_from_bhive -- \
    --gematria_input_csv=skl.csv \
    --gematria_output_tfrecord=skl.tfrecord \
    --gematria_throughput_source_name="bhive: skl"
INFO: Analyzed target //gematria/datasets/python:import_from_bhive (9 packages loaded, 3974 targets configured).
INFO: Found 1 target...
INFO: From Compiling llvm/lib/Support/Process.cpp:
In file included from external/llvm-project/llvm/lib/Support/Process.cpp:123:
external/llvm-project/llvm/lib/Support/Unix/Process.inc:101:10: warning: 'mallinfo' is deprecated [-Wdeprecated-declarations]
  mi = ::mallinfo();
         ^
/usr/include/malloc.h:114:48: note: 'mallinfo' has been explicitly marked deprecated here
extern struct mallinfo mallinfo (void) __THROW __MALLOC_DEPRECATED;
                                               ^
/usr/include/malloc.h:32:30: note: expanded from macro '__MALLOC_DEPRECATED'
# define __MALLOC_DEPRECATED __attribute_deprecated__
                             ^
/usr/include/x86_64-linux-gnu/sys/cdefs.h:339:51: note: expanded from macro '__attribute_deprecated__'
# define __attribute_deprecated__ __attribute__ ((__deprecated__))
                                                  ^
1 warning generated.
INFO: From Compiling llvm/lib/Support/Process.cpp [for tool]:
In file included from external/llvm-project/llvm/lib/Support/Process.cpp:123:
external/llvm-project/llvm/lib/Support/Unix/Process.inc:101:10: warning: 'mallinfo' is deprecated [-Wdeprecated-declarations]
  mi = ::mallinfo();
         ^
/usr/include/malloc.h:114:48: note: 'mallinfo' has been explicitly marked deprecated here
extern struct mallinfo mallinfo (void) __THROW __MALLOC_DEPRECATED;
                                               ^
/usr/include/malloc.h:32:30: note: expanded from macro '__MALLOC_DEPRECATED'
# define __MALLOC_DEPRECATED __attribute_deprecated__
                             ^
/usr/include/x86_64-linux-gnu/sys/cdefs.h:339:51: note: expanded from macro '__attribute_deprecated__'
# define __attribute_deprecated__ __attribute__ ((__deprecated__))
                                                  ^
1 warning generated.
Target //gematria/datasets/python:import_from_bhive up-to-date:
  bazel-bin/gematria/datasets/python/import_from_bhive
INFO: Elapsed time: 144.058s, Critical Path: 31.45s
INFO: 782 processes: 3 internal, 779 linux-sandbox.
INFO: Build completed successfully, 782 total actions
INFO: Running command line: bazel-bin/gematria/datasets/python/import_from_bhive '--gematria_input_csv=skl.csv' '--gematria_output_tfrecord=skl.tfrecord' '--gematria_throughput_source_name=bhive: skl'
2024-06-11 11:24:53.336711: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-11 11:24:53.338850: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-11 11:24:53.372145: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-11 11:24:53.372199: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-11 11:24:53.373893: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-11 11:24:53.382875: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-11 11:24:53.383089: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/hrong1/.cache/bazel/_bazel_hrong1/32246067180bfaeac7e17e4449bcdc84/execroot/com_google_gematria/bazel-out/k8-fastbuild/bin/gematria/datasets/python/import_from_bhive.runfiles/com_google_gematria/gematria/datasets/python/import_from_bhive.py", line 36, in <module>
    import tensorflow as tf
  File "/home/hrong1/gematria/env/lib/python3.11/site-packages/tensorflow/__init__.py", line 48, in <module>
    from tensorflow._api.v2 import __internal__
  File "/home/hrong1/gematria/env/lib/python3.11/site-packages/tensorflow/_api/v2/__internal__/__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "/home/hrong1/gematria/env/lib/python3.11/site-packages/tensorflow/_api/v2/__internal__/autograph/__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrong1/gematria/env/lib/python3.11/site-packages/tensorflow/python/autograph/core/ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "/home/hrong1/gematria/env/lib/python3.11/site-packages/tensorflow/python/autograph/utils/__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "/home/hrong1/gematria/env/lib/python3.11/site-packages/tensorflow/python/autograph/utils/context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "/home/hrong1/gematria/env/lib/python3.11/site-packages/tensorflow/python/framework/ops.py", line 44, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "/home/hrong1/gematria/env/lib/python3.11/site-packages/tensorflow/python/client/pywrap_tf_session.py", line 25, in <module>
    from tensorflow.python.util import tf_stack
  File "/home/hrong1/gematria/env/lib/python3.11/site-packages/tensorflow/python/util/tf_stack.py", line 22, in <module>
    from tensorflow.python.util import _tf_stack
ImportError: generic_type: cannot initialize type "StatusCode": an object with that name is already defined
```
I'm wondering if this is expected or if there is something wrong with my environment. My environment uses the same requirment.in as master except tensorflow-probability>=0.19.0 is changed to tensorflow-probability==0.23.0.

Any suggestion? Thanks!
Hongbo

**Comment by ronghongbo** [comment]
The version of tensorflow might be the issue. Upgrade with
```
pip3 install  --upgrade tensorflow
	tensorflow-ranking 0.5.5 requires tensorflow<2.16.0, but you have tensorflow 2.16.1 which is incompatible.
	Successfully installed keras-3.3.3 tensorboard-2.16.2 tensorflow-2.16.1
```
After this, the conversion seems to work, despite a conflict with the version of tensorflow-ranking
